---
title: "PSYC 593 final project"
author: "Huiyu Ding, Howard Tan, Hector Shi"
date: "2024-11-29"
output: html_document
---

prepare and clean files (here only looking at exp1 free view data)
```{r setup_data}

library(tidyverse)
library(ggplot2)
library(gghalves)
library(rprojroot) 
library(here) 

### Path variables ----

here_path <- here::here()
docs_path <- here::here("doc")           # Using here
data_path <- file.path(here_path, "data")
raw_data_path <- file.path(data_path, "raw")
processed_data_path <- file.path(data_path, "processed")
figures_path <- file.path(here_path, "results","figures")
heatmaps_path <- file.path(here_path, "results","heatmaps")
background_image_path <- file.path(raw_data_path, "howard_dataset", "screenshots", "exp1")

#read in raw file
data_fv <- read.csv(file.path(processed_data_path,"exp1_freeview.csv")) %>%
  dplyr::rename(trial = "original_TrialNum",
         subject = "participant",
         condition1_dnum = "num_distractors",
         condition2_sid = "singleton_id") %>%
  dplyr::select(trial,subject, condition1_dnum, condition2_sid, target_pos, singleton_pos, f1:f9)

data_search <- read.csv(file.path(processed_data_path,"exp1_search.csv")) %>%
  dplyr::rename(trial = "original_TrialNum",
         subject = "participant",
         condition1_dnum = "num_distractors",
         condition2_sid = "singleton_id") %>%
  dplyr::select(trial,subject, condition1_dnum, condition2_sid, target_pos, singleton_pos, f1:f8)

# extract only the last four numbers in the raw fixation data
extract_last_four_numeric <- function(cell) {
  # Remove outer square brackets
  cell <- gsub("^\\[|\\]$", "", cell)
  
  # Split by commas
  parts <- str_split(cell, ",\\s*")[[1]]
  
  # Extract last four elements
  last_four <- tail(parts, 4)
  
  # Clean up residual quotes and convert to numeric
  last_four <- as.numeric(gsub("'", "", last_four))
  
  return(last_four)
}

# Apply cleaning to each column
cleaned_data_fv <- data_fv %>%
  mutate(across(everything(), ~ map(.x, extract_last_four_numeric))) %>% 
  group_by(trial,subject) %>%
  pivot_longer(values_to = "fix", names_to = "fix_num", f1:f9) %>%
  mutate(fix = gsub("^c\\(|\\)$", "", fix),
         target_pos = gsub("^c\\(|\\)$", "", target_pos),
         singleton_pos = gsub("^c\\(|\\)$", "", singleton_pos)) %>%
  filter(fix != "NA") %>%
  separate(fix, into = c("x", "y", "duration", "onset"), sep = ",\\s*", convert = TRUE) %>%
  separate(target_pos, into = c("target_x", "target_y"), sep = ",\\s*", convert = TRUE) %>%
  separate(singleton_pos, into = c("singleton_x", "singleton_y"), sep = ",\\s*", convert = TRUE) %>%
  mutate(subject = as.numeric(subject),
         trial = as.numeric(trial)) %>%
  mutate(y = 1080 - y,
         target_y = 1080 - target_y,
         singleton_y = 1080 - singleton_y)


cleaned_data_search <- data_search %>%
  mutate(across(everything(), ~ map(.x, extract_last_four_numeric))) %>% 
  group_by(trial,subject) %>%
  pivot_longer(values_to = "fix", names_to = "fix_num", f1:f8) %>%
  mutate(fix = gsub("^c\\(|\\)$", "", fix),
         target_pos = gsub("^c\\(|\\)$", "", target_pos),
         singleton_pos = gsub("^c\\(|\\)$", "", singleton_pos))%>%
  filter(fix != "NA") %>%
  separate(fix, into = c("x", "y", "duration", "onset"), sep = ",\\s*", convert = TRUE) %>%
  separate(target_pos, into = c("target_x", "target_y"), sep = ",\\s*", convert = TRUE) %>%
  separate(singleton_pos, into = c("singleton_x", "singleton_y"), sep = ",\\s*", convert = TRUE) %>%
  mutate(subject = as.numeric(subject),
         trial = as.numeric(trial)) %>%
  mutate(y = 1080 - y,
         target_y = 1080 - target_y,
         singleton_y = 1080 - singleton_y)

```

generate summary variables and plot

```{r trial summaries}

calc_distance_function <- function(x1, y1, x2, y2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2)
}


generate_summaries_function <- function(data, subject = NULL, trial = NULL) {
  
  if (is.null(subject)) {
    subject <- unique(data$subject)
  }
  if (is.null(trial)) {
    trial <- unique(data$trial)
  }
  

  data <- data %>% 
    mutate(fix_num_value = as.numeric(gsub("f", "", fix_num)))
  
  average_fixations_per_sub <- data %>%
    group_by(subject) %>%
    summarise(avg_fix_sub = mean(max(fix_num_value)))%>%
    ungroup()
  
  average_fixations_per_trial <- data %>%
    group_by(trial) %>%
    summarise(avg_fix_trial = mean(max(fix_num_value))) %>%
    ungroup()
  
  sacc_amps <- data %>%
    arrange(trial, subject, fix_num_value) %>%
    group_by(trial, subject) %>%
    mutate(distance = calc_distance_function(x, y, lead(x), lead(y))) %>%
    summarise(total_distance = sum(distance, na.rm = TRUE)) 
  
  sacc_summaries_sub <- sacc_amps %>% 
    group_by(subject) %>%
    summarise(avg_sacc_amp = mean(total_distance)) 
  
  sacc_summaries_trial <- sacc_amps %>% 
    group_by(trial) %>%
    summarise(avg_sacc_amp = mean(total_distance)) 
  
  # print("\nAverage fixations by trial:")
  # print(average_fixations_per_trial)
  # 
  # print("\nAverage fixations by subject:")
  # print(average_fixations_per_sub)
  # 
  # print("\nAverage saccade amplitude by trial:")
  # print(sacc_summaries_trial)
  # 
  # print("\nAverage saccade amplitude by subject:")
  # print(sacc_summaries_sub)

  
  fix_sub_graph <- ggplot(data = average_fixations_per_sub, aes(x=avg_fix_sub))+
    geom_histogram(binwidth = 1)
  
  fix_trial_graph <- ggplot(data = average_fixations_per_trial, aes(x=avg_fix_trial))+
    geom_histogram(binwidth = 1)
  
  sacc_sub_graph <- ggplot(data = sacc_summaries_sub, aes(x=avg_sacc_amp))+
    geom_density()
  
  sacc_trial_graph <- ggplot(data = sacc_summaries_trial, aes(x=avg_sacc_amp))+
    geom_density()
  
  print(fix_sub_graph)
  print(fix_trial_graph)
  print(sacc_trial_graph)
  print(sacc_sub_graph)

}

fv_graphs <- generate_summaries_function(cleaned_data_fv)
s_graphs <- generate_summaries_function(cleaned_data_search)




combined_graph <- ggplot() +
  geom_density(data = fv_graphs$data, aes(x = avg_sacc_amp, color = "freeview"), alpha = 0.5) +
  geom_density(data = s_graphs$data, aes(x = avg_sacc_amp, color = "search"), alpha = 0.5) +
  scale_color_manual(values = c("freeview" = "blue", "search" = "red"),
                     name = "Data Source") +
  labs(x = "Average Saccade Amplitude",
       y = "Density",
       title = "Comparison of Saccade Amplitude Distributions") +
  theme_minimal()
print(combined_graph)

```



function for heat map and ordinal fixations
```{r heatmap functions}
library(MASS)
library(ggtern) #  Gaussian kernal calculation for heatmap
library(grid)
library(png)
library(ggimage) #package for image as background

heatmap_function <- function(data, subject_num = NULL, trial_num = NULL) {
  
  if (is.null(subject_num)) {
    subject_num <- unique(data$subject)
  }
  if (is.null(trial_num)) {
    trial_num <- unique(data$trial)
  }
  
  pattern <- paste0("*_trialnum_", trial_num, ".png")
  
  image_files <- list.files(path = background_image_path, 
                           pattern = pattern,
                           recursive = TRUE,  # search in subdirectories
                           full.names = TRUE) # get full path
  
  # Take the first matching file (assuming there's only one per trial number)
  image_path <- image_files[1]
  image <- png::readPNG(image_path)
  
  # Filter data for the selected subject and trial
  heatmap_df <- data %>% 
    filter(subject %in% subject_num) %>% 
    filter(trial %in% trial_num)
  
  target_x = unique(heatmap_df$target_x)
  target_y = unique(heatmap_df$target_y)
    
  if (nrow(heatmap_df) == 0) {
    stop("No data available for this subject and trial.")
   }
  
  # !!!!!!!! maybe no need to weight duration? !!!!!!!!!!!!!!!!!!!!!!
  
  # Compute bandwidth dynamically
  # bandwidth <- c(sd(heatmap_df$x) * 0.5, sd(heatmap_df$y) * 0.5)
  # kde_result <- with(heatmap_df, kde2d.weighted(x, y, w = duration, h = bandwidth, n = 100, lims = c(range(0,1920), range(0,1080))))
  # 
  # # Convert the KDE output to a dataframe for ggplot2
  # kde_df <- data.frame(
  #   x = rep(kde_result$x, each = length(kde_result$y)),
  #   y = rep(kde_result$y, times = length(kde_result$x)),
  #   density = as.vector(kde_result$z)
  # )
  
  # plot the graph
  graph <- ggplot(heatmap_df, aes(x = x, y = y, fill = density)) +
    annotation_custom(
      rasterGrob(image, width = unit(1, "npc"), height = unit(1, "npc")), 
      xmin = 0, xmax = 1920, ymin = 0, ymax = 1080
    ) +
    theme_minimal() +
    stat_density2d(aes(x = x, y =y, fill = ..level.., alpha = ..level.., weight = duration), 
                   size= 1, bins= 10, geom='polygon') +
    scale_alpha(range = c(0, 0.8), guide = "none") +  # Set alpha scale; 0 for no density
    scale_fill_gradient(low = "green", high = "red", guide = "none") +    
    labs(title = "Fixation Heatmap") +
    theme_minimal() +
    geom_rect(aes(xmin = 0, xmax = 1920, ymin = 0, ymax = 1080), fill = NA, color = "black", size = 1) +
    scale_x_continuous(breaks = seq(0, 1920, by = 480), limits = c(0, 1920)) + 
    scale_y_continuous(breaks = seq(0, 1080, by = 360), limits = c(0, 1080)) +   
    theme(panel.grid = element_blank(),  
          panel.border = element_blank(),
          plot.title = element_text(hjust = 0.5)) +
    ggtitle(paste("Heatmap for", "trial",trial_num,
                  "\n","# of distractors:",data$condition1_dnum,"and singleton condition",data$condition2_sid)) +
    geom_rect(data = heatmap_df, aes(xmin = target_x-20, xmax = target_x+20, ymin = target_y-20, ymax = target_y+20), fill = NA, alpha = 0.2, color = "black", size = 1) +
    annotate("text", x = target_x , y = target_y + 80, label = "target", size = 4, color = "black", fontface = "bold")+ 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())
    
  
  return(graph)
}

# graph the fixations made for specifed trial ____________________________________________________________
fixation_order_function <- function(data, subject_num, trial_num) {
  
  # Construct the background image file path

  pattern <- paste0("*_trialnum_", trial_num, ".png")
  
  image_files <- list.files(path = background_image_path, 
                           pattern = pattern,
                           recursive = TRUE,  # search in subdirectories
                           full.names = TRUE) # get full path
  
  # Take the first matching file (assuming there's only one per trial number)
  image_path <- image_files[1]
  image <- png::readPNG(image_path)
  
  fixation_df <- data %>% 
    filter(trial == trial_num) %>%
    filter(subject == subject_num) %>%
    group_by(subject,trial) %>%
    mutate(order = row_number())
  
  target_x = unique(fixation_df$target_x)
  target_y = unique(fixation_df$target_y)
  
  if (nrow(fixation_df) == 0) {
    stop("No data available for this subject and trial.")
   }
  
  # plot the graph
  graph <- ggplot(fixation_df, aes(x = x, y = y)) +
    theme_minimal() +
    annotation_custom(rasterGrob(image, width = unit(1, "npc"), height = unit(1, "npc")), 
      xmin = 0, xmax = 1920, ymin = 0, ymax = 1080) +
    theme_minimal() +
    geom_path(arrow = arrow(type = "closed", length = unit(0.2, "cm")), color = "orange", size = 1) +
    geom_point(size = 8, shape = 21, fill = "red", color = "red", alpha = 0.5) +  # Circles for fixations
    geom_text(aes(label = order), color = "white", size = 4, fontface = "bold", vjust = 0.5) +  # Numbers inside circles
    labs(title = "Fixation Plot") +
    scale_x_continuous(breaks = seq(0, 1920, by = 480), limits = c(0, 1920)) + 
    scale_y_continuous(breaks = seq(0, 1080, by = 360), limits = c(0, 1080)) +   
    coord_fixed() +  # Keep the aspect ratio of the image
    theme_minimal() +
    theme(
      panel.grid = element_blank(),  
      panel.border = element_blank(),
      plot.title = element_text(hjust = 0.5)
    ) +
    ggtitle(paste("Fixation plot for","trial",trial_num,
                  "\n","# of distractors:",data$condition1_dnum[1],"and singleton condition",data$condition2_sid[1])) +
    geom_rect(aes(xmin = target_x-20, xmax = target_x+20, ymin = target_y-20, ymax = target_y+20), 
              fill = NA, alpha = 0.2, color = "black", size = 1) +
    annotate("text", x = target_x , y = target_y + 80, label = "target", size = 4, color = "black", fontface = "bold")+ 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())
  
  return(graph)
}
```

graph heatmap and fixations
```{r graphs}
# if no input for subject_num, graph all subjects
heatmap_graph <- heatmap_function(cleaned_data_search, trial_num = 23)
fixation_graph <- fixation_order_function(cleaned_data_search, 1, 15)

heatmap_graph
fixation_graph
```


